[package]
name = "tbl-slint"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tbl-core = { path = "../core" }
slint = "1.16.1"
clap = { version = "4", features = ["derive"] }
log = "0.4"
simplelog = "0.12"
chrono = "0.4"
anyhow = "1"
arboard = "3"
rfd = "0.15"

[build-dependencies]
slint-build = "1.16.1"
