// Auto-generated by tablet. Do not edit.
//
// 公共运行时：Tuple 别名 / SepConfig / 字符串切分与基础类型解析。
// 所有生成的 *.cpp 都会包含此头文件。

#pragma once

#include <cstdint>
#include <functional>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace {{NAMESPACE}} {

template <typename A, typename B>
using Tuple2 = std::tuple<A, B>;
template <typename A, typename B, typename C>
using Tuple3 = std::tuple<A, B, C>;
template <typename A, typename B, typename C, typename D>
using Tuple4 = std::tuple<A, B, C, D>;

struct SepConfig {
    std::string list = ";";
    std::string set = ";";
    std::string tuple2 = ",";
    std::string tuple3 = ",";
    std::string tuple4 = ",";
    std::string map_kv = ":";
    std::string map_entry = ";";
    std::string list_tuple2_tuple = ",";
    std::string list_tuple2_list = ";";
    std::string list_tuple3_tuple = ",";
    std::string list_tuple3_list = ";";
    std::string list_tuple4_tuple = ",";
    std::string list_tuple4_list = ";";
    std::string map_tuple2_kv = ":";
    std::string map_tuple2_tuple = ",";
    std::string map_tuple2_entry = ";";
    std::string map_tuple3_kv = ":";
    std::string map_tuple3_tuple = ",";
    std::string map_tuple3_entry = ";";
    std::string map_tuple4_kv = ":";
    std::string map_tuple4_tuple = ",";
    std::string map_tuple4_entry = ";";
    std::string map_list_kv = ":";
    std::string map_list_item = ",";
    std::string map_list_entry = ";";
};

inline std::vector<std::string> tbl_split(const std::string& s, const std::string& sep) {
    std::vector<std::string> out;
    if (s.empty()) return out;
    if (sep.empty()) { out.push_back(s); return out; }
    size_t start = 0;
    while (true) {
        size_t pos = s.find(sep, start);
        if (pos == std::string::npos) { out.emplace_back(s.substr(start)); break; }
        out.emplace_back(s.substr(start, pos - start));
        start = pos + sep.size();
    }
    return out;
}

inline std::vector<std::string> tbl_splitn(const std::string& s, const std::string& sep, size_t n) {
    std::vector<std::string> out;
    if (n == 0 || s.empty()) return out;
    if (n == 1 || sep.empty()) { out.push_back(s); return out; }
    size_t start = 0;
    for (size_t i = 0; i + 1 < n; ++i) {
        size_t pos = s.find(sep, start);
        if (pos == std::string::npos) break;
        out.emplace_back(s.substr(start, pos - start));
        start = pos + sep.size();
    }
    out.emplace_back(s.substr(start));
    return out;
}

inline int32_t parse_int32(const std::string& s) {
    if (s.empty()) return 0;
    try { return static_cast<int32_t>(std::stol(s)); } catch (...) { return 0; }
}
inline int64_t parse_int64(const std::string& s) {
    if (s.empty()) return 0;
    try { return std::stoll(s); } catch (...) { return 0; }
}
inline float parse_float(const std::string& s) {
    if (s.empty()) return 0.0f;
    try { return std::stof(s); } catch (...) { return 0.0f; }
}
inline double parse_double(const std::string& s) {
    if (s.empty()) return 0.0;
    try { return std::stod(s); } catch (...) { return 0.0; }
}
inline bool parse_bool(const std::string& s) {
    return s == "true" || s == "1";
}
inline std::string parse_str(const std::string& s) { return s; }

template <typename T>
inline std::vector<T> parse_list(const std::string& raw, const std::string& sep,
                                 std::function<T(const std::string&)> f) {
    std::vector<T> out;
    if (raw.empty()) return out;
    for (auto& part : tbl_split(raw, sep)) out.push_back(f(part));
    return out;
}

template <typename T>
inline std::unordered_set<T> parse_set(const std::string& raw, const std::string& sep,
                                       std::function<T(const std::string&)> f) {
    std::unordered_set<T> out;
    if (raw.empty()) return out;
    for (auto& part : tbl_split(raw, sep)) out.insert(f(part));
    return out;
}

template <typename K, typename V>
inline std::unordered_map<K, V> parse_map(const std::string& raw,
                                          const std::string& kv_sep,
                                          const std::string& entry_sep,
                                          std::function<K(const std::string&)> fk,
                                          std::function<V(const std::string&)> fv) {
    std::unordered_map<K, V> out;
    if (raw.empty()) return out;
    for (auto& entry : tbl_split(raw, entry_sep)) {
        auto kv = tbl_splitn(entry, kv_sep, 2);
        if (kv.size() == 2) out.emplace(fk(kv[0]), fv(kv[1]));
    }
    return out;
}

template <typename A, typename B>
inline Tuple2<A, B> parse_tuple2(const std::string& raw, const std::string& sep,
                                 std::function<A(const std::string&)> fa,
                                 std::function<B(const std::string&)> fb) {
    auto parts = tbl_splitn(raw, sep, 2);
    if (parts.size() != 2) return {};
    return std::make_tuple(fa(parts[0]), fb(parts[1]));
}

template <typename A, typename B, typename C>
inline Tuple3<A, B, C> parse_tuple3(const std::string& raw, const std::string& sep,
                                    std::function<A(const std::string&)> fa,
                                    std::function<B(const std::string&)> fb,
                                    std::function<C(const std::string&)> fc) {
    auto parts = tbl_splitn(raw, sep, 3);
    if (parts.size() != 3) return {};
    return std::make_tuple(fa(parts[0]), fb(parts[1]), fc(parts[2]));
}

template <typename A, typename B, typename C, typename D>
inline Tuple4<A, B, C, D> parse_tuple4(const std::string& raw, const std::string& sep,
                                       std::function<A(const std::string&)> fa,
                                       std::function<B(const std::string&)> fb,
                                       std::function<C(const std::string&)> fc,
                                       std::function<D(const std::string&)> fd) {
    auto parts = tbl_splitn(raw, sep, 4);
    if (parts.size() != 4) return {};
    return std::make_tuple(fa(parts[0]), fb(parts[1]), fc(parts[2]), fd(parts[3]));
}

}  // namespace {{NAMESPACE}}
