// Auto-generated by tablet. Do not edit.
//
// .NET 通用 Loader：File.ReadAllText + System.Text.Json。
// 用法：
//   {{NAMESPACE}}.Loader.LoadAll("path/to/data/json");

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;

namespace {{NAMESPACE}}
{
    public static class Loader
    {
        public static void LoadAll(string dataDir)
        {
            if (!Directory.Exists(dataDir))
                throw new DirectoryNotFoundException("data dir not found: " + dataDir);
            foreach (var path in Directory.EnumerateFiles(dataDir, "*.json", SearchOption.AllDirectories))
            {
                var rel = Path.GetRelativePath(dataDir, path);
                var key = rel.Replace(Path.DirectorySeparatorChar, '/');
                if (key.EndsWith(".json", StringComparison.Ordinal))
                    key = key.Substring(0, key.Length - 5);
                LoadOne(path, key);
            }
        }

        static void LoadOne(string path, string key)
        {
            using var fs = File.OpenRead(path);
            using var doc = JsonDocument.Parse(fs);
            var root = doc.RootElement;

            var sep = new SepConfig();
            if (root.TryGetProperty("_sep", out var sepEl) && sepEl.ValueKind == JsonValueKind.Object)
                ApplySep(sep, sepEl);

            if (!root.TryGetProperty("data", out var data)) return;

            if (TblRegistry.Tables.TryGetValue(key, out var tableLoader))
            {
                var rows = new List<Dictionary<string, string>>();
                if (data.ValueKind == JsonValueKind.Array)
                    foreach (var row in data.EnumerateArray()) rows.Add(ObjectToStrMap(row));
                tableLoader(rows, sep);
                return;
            }
            if (TblRegistry.Constants.TryGetValue(key, out var constLoader))
            {
                constLoader(ObjectToStrMap(data), sep);
            }
        }

        static Dictionary<string, string> ObjectToStrMap(JsonElement obj)
        {
            var map = new Dictionary<string, string>();
            if (obj.ValueKind != JsonValueKind.Object) return map;
            foreach (var prop in obj.EnumerateObject()) map[prop.Name] = ValueToStr(prop.Value);
            return map;
        }

        static string ValueToStr(JsonElement v) => v.ValueKind switch
        {
            JsonValueKind.Null => string.Empty,
            JsonValueKind.String => v.GetString() ?? string.Empty,
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            JsonValueKind.Number => v.GetRawText(),
            _ => v.GetRawText(),
        };

        static void ApplySep(SepConfig cfg, JsonElement obj)
        {
            string Get(string k) => obj.TryGetProperty(k, out var e) && e.ValueKind == JsonValueKind.String ? e.GetString() : null;
            cfg.List = Get("list") ?? cfg.List;
            cfg.Set = Get("set") ?? cfg.Set;
            cfg.Tuple2 = Get("tuple2") ?? cfg.Tuple2;
            cfg.Tuple3 = Get("tuple3") ?? cfg.Tuple3;
            cfg.Tuple4 = Get("tuple4") ?? cfg.Tuple4;
            cfg.MapKv = Get("map_kv") ?? cfg.MapKv;
            cfg.MapEntry = Get("map_entry") ?? cfg.MapEntry;
            cfg.ListTuple2Tuple = Get("list_tuple2_tuple") ?? cfg.ListTuple2Tuple;
            cfg.ListTuple2List = Get("list_tuple2_list") ?? cfg.ListTuple2List;
            cfg.ListTuple3Tuple = Get("list_tuple3_tuple") ?? cfg.ListTuple3Tuple;
            cfg.ListTuple3List = Get("list_tuple3_list") ?? cfg.ListTuple3List;
            cfg.ListTuple4Tuple = Get("list_tuple4_tuple") ?? cfg.ListTuple4Tuple;
            cfg.ListTuple4List = Get("list_tuple4_list") ?? cfg.ListTuple4List;
            cfg.MapTuple2Kv = Get("map_tuple2_kv") ?? cfg.MapTuple2Kv;
            cfg.MapTuple2Tuple = Get("map_tuple2_tuple") ?? cfg.MapTuple2Tuple;
            cfg.MapTuple2Entry = Get("map_tuple2_entry") ?? cfg.MapTuple2Entry;
            cfg.MapTuple3Kv = Get("map_tuple3_kv") ?? cfg.MapTuple3Kv;
            cfg.MapTuple3Tuple = Get("map_tuple3_tuple") ?? cfg.MapTuple3Tuple;
            cfg.MapTuple3Entry = Get("map_tuple3_entry") ?? cfg.MapTuple3Entry;
            cfg.MapTuple4Kv = Get("map_tuple4_kv") ?? cfg.MapTuple4Kv;
            cfg.MapTuple4Tuple = Get("map_tuple4_tuple") ?? cfg.MapTuple4Tuple;
            cfg.MapTuple4Entry = Get("map_tuple4_entry") ?? cfg.MapTuple4Entry;
            cfg.MapListKv = Get("map_list_kv") ?? cfg.MapListKv;
            cfg.MapListItem = Get("map_list_item") ?? cfg.MapListItem;
            cfg.MapListEntry = Get("map_list_entry") ?? cfg.MapListEntry;
        }
    }
}
