// Auto-generated by tablet. Do not edit.
//
// 公共运行时：Tuple / SepConfig / 字符串切分与基础类型解析。
// 三个 runtime（dotnet / unity / godot）共用本文件。

using System;
using System.Collections.Generic;
using System.Globalization;

namespace {{NAMESPACE}}
{
    public readonly struct Tuple2<TA, TB>
    {
        public readonly TA Item1;
        public readonly TB Item2;
        public Tuple2(TA a, TB b) { Item1 = a; Item2 = b; }
    }

    public readonly struct Tuple3<TA, TB, TC>
    {
        public readonly TA Item1;
        public readonly TB Item2;
        public readonly TC Item3;
        public Tuple3(TA a, TB b, TC c) { Item1 = a; Item2 = b; Item3 = c; }
    }

    public readonly struct Tuple4<TA, TB, TC, TD>
    {
        public readonly TA Item1;
        public readonly TB Item2;
        public readonly TC Item3;
        public readonly TD Item4;
        public Tuple4(TA a, TB b, TC c, TD d) { Item1 = a; Item2 = b; Item3 = c; Item4 = d; }
    }

    public sealed class SepConfig
    {
        public string List = ";";
        public string Set = ";";
        public string Tuple2 = ",";
        public string Tuple3 = ",";
        public string Tuple4 = ",";
        public string MapKv = ":";
        public string MapEntry = ";";
        public string ListTuple2Tuple = ",";
        public string ListTuple2List = ";";
        public string ListTuple3Tuple = ",";
        public string ListTuple3List = ";";
        public string ListTuple4Tuple = ",";
        public string ListTuple4List = ";";
        public string MapTuple2Kv = ":";
        public string MapTuple2Tuple = ",";
        public string MapTuple2Entry = ";";
        public string MapTuple3Kv = ":";
        public string MapTuple3Tuple = ",";
        public string MapTuple3Entry = ";";
        public string MapTuple4Kv = ":";
        public string MapTuple4Tuple = ",";
        public string MapTuple4Entry = ";";
        public string MapListKv = ":";
        public string MapListItem = ",";
        public string MapListEntry = ";";
    }

    public static class TblParse
    {
        public static List<string> Split(string s, string sep)
        {
            var list = new List<string>();
            if (string.IsNullOrEmpty(s)) return list;
            if (string.IsNullOrEmpty(sep)) { list.Add(s); return list; }
            int start = 0;
            while (true)
            {
                int idx = s.IndexOf(sep, start, StringComparison.Ordinal);
                if (idx < 0) { list.Add(s.Substring(start)); break; }
                list.Add(s.Substring(start, idx - start));
                start = idx + sep.Length;
            }
            return list;
        }

        public static List<string> SplitN(string s, string sep, int n)
        {
            var list = new List<string>();
            if (n <= 0 || string.IsNullOrEmpty(s)) return list;
            if (n == 1 || string.IsNullOrEmpty(sep)) { list.Add(s); return list; }
            int start = 0;
            for (int i = 0; i + 1 < n; i++)
            {
                int idx = s.IndexOf(sep, start, StringComparison.Ordinal);
                if (idx < 0) break;
                list.Add(s.Substring(start, idx - start));
                start = idx + sep.Length;
            }
            list.Add(s.Substring(start));
            return list;
        }

        public static int ParseInt32(string s)
        {
            if (string.IsNullOrEmpty(s)) return 0;
            return int.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v) ? v : 0;
        }

        public static long ParseInt64(string s)
        {
            if (string.IsNullOrEmpty(s)) return 0L;
            return long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v) ? v : 0L;
        }

        public static float ParseFloat(string s)
        {
            if (string.IsNullOrEmpty(s)) return 0f;
            return float.TryParse(s, NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : 0f;
        }

        public static double ParseDouble(string s)
        {
            if (string.IsNullOrEmpty(s)) return 0d;
            return double.TryParse(s, NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : 0d;
        }

        public static bool ParseBool(string s) => s == "true" || s == "1";

        public static string ParseStr(string s) => s ?? string.Empty;

        public static List<T> ParseList<T>(string raw, string sep, Func<string, T> f)
        {
            var list = new List<T>();
            if (string.IsNullOrEmpty(raw)) return list;
            foreach (var part in Split(raw, sep)) list.Add(f(part));
            return list;
        }

        public static HashSet<T> ParseSet<T>(string raw, string sep, Func<string, T> f)
        {
            var set = new HashSet<T>();
            if (string.IsNullOrEmpty(raw)) return set;
            foreach (var part in Split(raw, sep)) set.Add(f(part));
            return set;
        }

        public static Dictionary<TK, TV> ParseMap<TK, TV>(string raw, string kvSep, string entrySep,
                                                          Func<string, TK> fk, Func<string, TV> fv)
        {
            var map = new Dictionary<TK, TV>();
            if (string.IsNullOrEmpty(raw)) return map;
            foreach (var entry in Split(raw, entrySep))
            {
                var kv = SplitN(entry, kvSep, 2);
                if (kv.Count == 2) map[fk(kv[0])] = fv(kv[1]);
            }
            return map;
        }

        public static Tuple2<TA, TB> ParseTuple2<TA, TB>(string raw, string sep,
                                                        Func<string, TA> fa, Func<string, TB> fb)
        {
            var p = SplitN(raw, sep, 2);
            if (p.Count != 2) return default;
            return new Tuple2<TA, TB>(fa(p[0]), fb(p[1]));
        }

        public static Tuple3<TA, TB, TC> ParseTuple3<TA, TB, TC>(string raw, string sep,
                                                                Func<string, TA> fa, Func<string, TB> fb, Func<string, TC> fc)
        {
            var p = SplitN(raw, sep, 3);
            if (p.Count != 3) return default;
            return new Tuple3<TA, TB, TC>(fa(p[0]), fb(p[1]), fc(p[2]));
        }

        public static Tuple4<TA, TB, TC, TD> ParseTuple4<TA, TB, TC, TD>(string raw, string sep,
                                                                        Func<string, TA> fa, Func<string, TB> fb, Func<string, TC> fc, Func<string, TD> fd)
        {
            var p = SplitN(raw, sep, 4);
            if (p.Count != 4) return default;
            return new Tuple4<TA, TB, TC, TD>(fa(p[0]), fb(p[1]), fc(p[2]), fd(p[3]));
        }
    }

    public static class TblRegistry
    {
        public delegate void TableLoader(List<Dictionary<string, string>> rows, SepConfig sep);
        public delegate void ConstantLoader(Dictionary<string, string> row, SepConfig sep);

        public static readonly Dictionary<string, TableLoader> Tables = new();
        public static readonly Dictionary<string, ConstantLoader> Constants = new();
    }
}
