// Auto-generated by tbl-tool. Do not edit.
//
// Unity Loader：Resources.Load<TextAsset>(...) + Newtonsoft.Json (Unity 项目通常已自带)。
// 数据需放在 Resources/<dataDir>/ 下并以 .json 后缀。
// 用法：
//   {{NAMESPACE}}.Loader.LoadAll("data");  // 对应 Resources/data/*.json
//
// Note (IL2CPP)：Newtonsoft 在 IL2CPP 平台需 link.xml 保留泛型；属于 Unity 项目工程问题。

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace {{NAMESPACE}}
{
    public static class Loader
    {
        public static void LoadAll(string resourcesSubdir)
        {
            // 一次性加载该子目录下所有 TextAsset；Unity 不支持运行时枚举 Resources，
            // 调用方需在编辑期保证 .json 文件名 stem 与表/常量名一致。
            var assets = Resources.LoadAll<TextAsset>(resourcesSubdir);
            foreach (var ta in assets)
            {
                LoadOne(ta.name, ta.text);
            }
        }

        public static void LoadOne(string key, string jsonText)
        {
            var doc = JObject.Parse(jsonText);
            var sep = new SepConfig();
            if (doc["_sep"] is JObject sepObj) ApplySep(sep, sepObj);
            var data = doc["data"];
            if (data == null) return;

            if (TblRegistry.Tables.TryGetValue(key, out var tableLoader))
            {
                var rows = new List<Dictionary<string, string>>();
                if (data is JArray arr)
                    foreach (var row in arr) rows.Add(ObjectToStrMap(row as JObject));
                tableLoader(rows, sep);
                return;
            }
            if (TblRegistry.Constants.TryGetValue(key, out var constLoader))
            {
                constLoader(ObjectToStrMap(data as JObject), sep);
            }
        }

        static Dictionary<string, string> ObjectToStrMap(JObject obj)
        {
            var map = new Dictionary<string, string>();
            if (obj == null) return map;
            foreach (var prop in obj.Properties()) map[prop.Name] = TokenToStr(prop.Value);
            return map;
        }

        static string TokenToStr(JToken v) => v?.Type switch
        {
            null => string.Empty,
            JTokenType.Null => string.Empty,
            JTokenType.String => v.Value<string>() ?? string.Empty,
            JTokenType.Boolean => v.Value<bool>() ? "true" : "false",
            JTokenType.Integer => v.Value<long>().ToString(System.Globalization.CultureInfo.InvariantCulture),
            JTokenType.Float => v.Value<double>().ToString(System.Globalization.CultureInfo.InvariantCulture),
            _ => v.ToString(Newtonsoft.Json.Formatting.None),
        };

        static void ApplySep(SepConfig cfg, JObject obj)
        {
            string Get(string k) => obj[k]?.Type == JTokenType.String ? obj[k].Value<string>() : null;
            cfg.List = Get("list") ?? cfg.List;
            cfg.Set = Get("set") ?? cfg.Set;
            cfg.Tuple2 = Get("tuple2") ?? cfg.Tuple2;
            cfg.Tuple3 = Get("tuple3") ?? cfg.Tuple3;
            cfg.Tuple4 = Get("tuple4") ?? cfg.Tuple4;
            cfg.MapKv = Get("map_kv") ?? cfg.MapKv;
            cfg.MapEntry = Get("map_entry") ?? cfg.MapEntry;
            cfg.ListTuple2Tuple = Get("list_tuple2_tuple") ?? cfg.ListTuple2Tuple;
            cfg.ListTuple2List = Get("list_tuple2_list") ?? cfg.ListTuple2List;
            cfg.ListTuple3Tuple = Get("list_tuple3_tuple") ?? cfg.ListTuple3Tuple;
            cfg.ListTuple3List = Get("list_tuple3_list") ?? cfg.ListTuple3List;
            cfg.ListTuple4Tuple = Get("list_tuple4_tuple") ?? cfg.ListTuple4Tuple;
            cfg.ListTuple4List = Get("list_tuple4_list") ?? cfg.ListTuple4List;
            cfg.MapTuple2Kv = Get("map_tuple2_kv") ?? cfg.MapTuple2Kv;
            cfg.MapTuple2Tuple = Get("map_tuple2_tuple") ?? cfg.MapTuple2Tuple;
            cfg.MapTuple2Entry = Get("map_tuple2_entry") ?? cfg.MapTuple2Entry;
            cfg.MapTuple3Kv = Get("map_tuple3_kv") ?? cfg.MapTuple3Kv;
            cfg.MapTuple3Tuple = Get("map_tuple3_tuple") ?? cfg.MapTuple3Tuple;
            cfg.MapTuple3Entry = Get("map_tuple3_entry") ?? cfg.MapTuple3Entry;
            cfg.MapTuple4Kv = Get("map_tuple4_kv") ?? cfg.MapTuple4Kv;
            cfg.MapTuple4Tuple = Get("map_tuple4_tuple") ?? cfg.MapTuple4Tuple;
            cfg.MapTuple4Entry = Get("map_tuple4_entry") ?? cfg.MapTuple4Entry;
            cfg.MapListKv = Get("map_list_kv") ?? cfg.MapListKv;
            cfg.MapListItem = Get("map_list_item") ?? cfg.MapListItem;
            cfg.MapListEntry = Get("map_list_entry") ?? cfg.MapListEntry;
        }
    }
}
