// Auto-generated by tbl-tool. Do not edit.
//
// Godot 4.x C# (Mono) Loader：FileAccess + Godot.Json。
// 用法：
//   {{NAMESPACE}}.Loader.LoadAll("res://data/json");
//
// 数据复用 tbl-tool --json 输出。

using System;
using System.Collections.Generic;
using Godot;

namespace {{NAMESPACE}}
{
    public static class Loader
    {
        public static void LoadAll(string dataDir)
        {
            using var dir = DirAccess.Open(dataDir);
            if (dir == null) throw new System.IO.DirectoryNotFoundException("data dir not found: " + dataDir);
            ScanDir(dataDir, "");
        }

        static void ScanDir(string root, string sub)
        {
            var fullDir = string.IsNullOrEmpty(sub) ? root : $"{root}/{sub}";
            using var dir = DirAccess.Open(fullDir);
            if (dir == null) return;
            dir.ListDirBegin();
            string entry;
            while (!string.IsNullOrEmpty(entry = dir.GetNext()))
            {
                if (entry == "." || entry == "..") continue;
                var rel = string.IsNullOrEmpty(sub) ? entry : $"{sub}/{entry}";
                if (dir.CurrentIsDir())
                {
                    ScanDir(root, rel);
                    continue;
                }
                if (!entry.EndsWith(".json", StringComparison.Ordinal)) continue;
                var key = rel.Substring(0, rel.Length - 5);
                LoadOne($"{root}/{rel}", key);
            }
            dir.ListDirEnd();
        }

        static void LoadOne(string path, string key)
        {
            using var f = FileAccess.Open(path, FileAccess.ModeFlags.Read);
            if (f == null) throw new System.IO.IOException("cannot open: " + path);
            var text = f.GetAsText();
            var parsed = Json.ParseString(text);
            if (parsed.Obj is not Godot.Collections.Dictionary doc) return;

            var sep = new SepConfig();
            if (doc.TryGetValue("_sep", out var sepVar)
                && sepVar.Obj is Godot.Collections.Dictionary sepObj)
                ApplySep(sep, sepObj);

            if (!doc.TryGetValue("data", out var dataVar)) return;

            if (TblRegistry.Tables.TryGetValue(key, out var tableLoader))
            {
                var rows = new List<Dictionary<string, string>>();
                if (dataVar.Obj is Godot.Collections.Array arr)
                    foreach (var row in arr)
                        if (row.Obj is Godot.Collections.Dictionary d)
                            rows.Add(ObjectToStrMap(d));
                tableLoader(rows, sep);
                return;
            }
            if (TblRegistry.Constants.TryGetValue(key, out var constLoader)
                && dataVar.Obj is Godot.Collections.Dictionary cd)
            {
                constLoader(ObjectToStrMap(cd), sep);
            }
        }

        static Dictionary<string, string> ObjectToStrMap(Godot.Collections.Dictionary obj)
        {
            var map = new Dictionary<string, string>();
            foreach (var k in obj.Keys)
            {
                var key = k.AsString();
                map[key] = ValueToStr(obj[k]);
            }
            return map;
        }

        static string ValueToStr(Variant v) => v.VariantType switch
        {
            Variant.Type.Nil => string.Empty,
            Variant.Type.String => v.AsString(),
            Variant.Type.StringName => v.AsString(),
            Variant.Type.Bool => v.AsBool() ? "true" : "false",
            Variant.Type.Int => v.AsInt64().ToString(System.Globalization.CultureInfo.InvariantCulture),
            Variant.Type.Float => v.AsDouble().ToString(System.Globalization.CultureInfo.InvariantCulture),
            _ => v.ToString(),
        };

        static void ApplySep(SepConfig cfg, Godot.Collections.Dictionary obj)
        {
            string Get(string k) => obj.TryGetValue(k, out var v) && v.VariantType == Variant.Type.String ? v.AsString() : null;
            cfg.List = Get("list") ?? cfg.List;
            cfg.Set = Get("set") ?? cfg.Set;
            cfg.Tuple2 = Get("tuple2") ?? cfg.Tuple2;
            cfg.Tuple3 = Get("tuple3") ?? cfg.Tuple3;
            cfg.Tuple4 = Get("tuple4") ?? cfg.Tuple4;
            cfg.MapKv = Get("map_kv") ?? cfg.MapKv;
            cfg.MapEntry = Get("map_entry") ?? cfg.MapEntry;
            cfg.ListTuple2Tuple = Get("list_tuple2_tuple") ?? cfg.ListTuple2Tuple;
            cfg.ListTuple2List = Get("list_tuple2_list") ?? cfg.ListTuple2List;
            cfg.ListTuple3Tuple = Get("list_tuple3_tuple") ?? cfg.ListTuple3Tuple;
            cfg.ListTuple3List = Get("list_tuple3_list") ?? cfg.ListTuple3List;
            cfg.ListTuple4Tuple = Get("list_tuple4_tuple") ?? cfg.ListTuple4Tuple;
            cfg.ListTuple4List = Get("list_tuple4_list") ?? cfg.ListTuple4List;
            cfg.MapTuple2Kv = Get("map_tuple2_kv") ?? cfg.MapTuple2Kv;
            cfg.MapTuple2Tuple = Get("map_tuple2_tuple") ?? cfg.MapTuple2Tuple;
            cfg.MapTuple2Entry = Get("map_tuple2_entry") ?? cfg.MapTuple2Entry;
            cfg.MapTuple3Kv = Get("map_tuple3_kv") ?? cfg.MapTuple3Kv;
            cfg.MapTuple3Tuple = Get("map_tuple3_tuple") ?? cfg.MapTuple3Tuple;
            cfg.MapTuple3Entry = Get("map_tuple3_entry") ?? cfg.MapTuple3Entry;
            cfg.MapTuple4Kv = Get("map_tuple4_kv") ?? cfg.MapTuple4Kv;
            cfg.MapTuple4Tuple = Get("map_tuple4_tuple") ?? cfg.MapTuple4Tuple;
            cfg.MapTuple4Entry = Get("map_tuple4_entry") ?? cfg.MapTuple4Entry;
            cfg.MapListKv = Get("map_list_kv") ?? cfg.MapListKv;
            cfg.MapListItem = Get("map_list_item") ?? cfg.MapListItem;
            cfg.MapListEntry = Get("map_list_entry") ?? cfg.MapListEntry;
        }
    }
}
