// Auto-generated by tablet. Do not edit.
//
// Loader：注册 + 遍历 dataDir 下的 .json，按文件名 stem 匹配到对应解析回调。
// 依赖 nlohmann/json (header-only)。如需 RapidJSON，请按相同形态重写本文件。

#pragma once

#include "tbl.h"

#include <filesystem>
#include <fstream>
#include <functional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

#ifdef TBL_JSON_LIB_NLOHMANN
#include <nlohmann/json.hpp>
#endif

namespace {{NAMESPACE}} {

using TableLoader = std::function<void(const std::vector<std::unordered_map<std::string, std::string>>&, const SepConfig&)>;
using ConstantLoader = std::function<void(const std::unordered_map<std::string, std::string>&, const SepConfig&)>;

inline std::unordered_map<std::string, TableLoader>& table_registry() {
    static std::unordered_map<std::string, TableLoader> r; return r;
}
inline std::unordered_map<std::string, ConstantLoader>& constant_registry() {
    static std::unordered_map<std::string, ConstantLoader> r; return r;
}

struct TableRegister { TableRegister(const std::string& k, TableLoader f) { table_registry()[k] = std::move(f); } };
struct ConstantRegister { ConstantRegister(const std::string& k, ConstantLoader f) { constant_registry()[k] = std::move(f); } };

#ifdef TBL_JSON_LIB_NLOHMANN

inline std::string json_to_str(const nlohmann::json& v) {
    if (v.is_null()) return "";
    if (v.is_string()) return v.get<std::string>();
    if (v.is_boolean()) return v.get<bool>() ? "true" : "false";
    if (v.is_number_integer()) return std::to_string(v.get<int64_t>());
    if (v.is_number_unsigned()) return std::to_string(v.get<uint64_t>());
    if (v.is_number_float()) {
        std::ostringstream ss; ss << v.get<double>(); return ss.str();
    }
    return v.dump();
}

inline std::unordered_map<std::string, std::string> json_obj_to_str_map(const nlohmann::json& obj) {
    std::unordered_map<std::string, std::string> out;
    if (!obj.is_object()) return out;
    for (auto it = obj.begin(); it != obj.end(); ++it) {
        out[it.key()] = json_to_str(it.value());
    }
    return out;
}

inline SepConfig sep_from_json(const nlohmann::json& sep_obj) {
    SepConfig cfg;
    if (!sep_obj.is_object()) return cfg;
    auto get = [&](const char* k, std::string& out) {
        if (sep_obj.contains(k) && sep_obj[k].is_string()) out = sep_obj[k].get<std::string>();
    };
    get("list", cfg.list);
    get("set", cfg.set);
    get("tuple2", cfg.tuple2);
    get("tuple3", cfg.tuple3);
    get("tuple4", cfg.tuple4);
    get("map_kv", cfg.map_kv);
    get("map_entry", cfg.map_entry);
    get("list_tuple2_tuple", cfg.list_tuple2_tuple);
    get("list_tuple2_list", cfg.list_tuple2_list);
    get("list_tuple3_tuple", cfg.list_tuple3_tuple);
    get("list_tuple3_list", cfg.list_tuple3_list);
    get("list_tuple4_tuple", cfg.list_tuple4_tuple);
    get("list_tuple4_list", cfg.list_tuple4_list);
    get("map_tuple2_kv", cfg.map_tuple2_kv);
    get("map_tuple2_tuple", cfg.map_tuple2_tuple);
    get("map_tuple2_entry", cfg.map_tuple2_entry);
    get("map_tuple3_kv", cfg.map_tuple3_kv);
    get("map_tuple3_tuple", cfg.map_tuple3_tuple);
    get("map_tuple3_entry", cfg.map_tuple3_entry);
    get("map_tuple4_kv", cfg.map_tuple4_kv);
    get("map_tuple4_tuple", cfg.map_tuple4_tuple);
    get("map_tuple4_entry", cfg.map_tuple4_entry);
    get("map_list_kv", cfg.map_list_kv);
    get("map_list_item", cfg.map_list_item);
    get("map_list_entry", cfg.map_list_entry);
    return cfg;
}

inline void load_one(const std::filesystem::path& path, const std::string& key) {
    std::ifstream ifs(path);
    if (!ifs) throw std::runtime_error("cannot open: " + path.string());
    nlohmann::json doc; ifs >> doc;

    SepConfig sep;
    if (doc.contains("_sep")) sep = sep_from_json(doc["_sep"]);

    const auto& data = doc["data"];

    auto tit = table_registry().find(key);
    if (tit != table_registry().end()) {
        std::vector<std::unordered_map<std::string, std::string>> rows;
        if (data.is_array()) {
            for (const auto& r : data) rows.push_back(json_obj_to_str_map(r));
        }
        tit->second(rows, sep);
        return;
    }

    auto cit = constant_registry().find(key);
    if (cit != constant_registry().end()) {
        cit->second(json_obj_to_str_map(data), sep);
        return;
    }
    // 未注册的文件，忽略
}

/// 加载 data_dir 下所有 .json，按 stem (去 .json 后缀) 匹配 registry。
inline void init_json(const std::string& data_dir) {
    namespace fs = std::filesystem;
    if (!fs::exists(data_dir)) throw std::runtime_error("data dir not found: " + data_dir);
    for (auto& e : fs::recursive_directory_iterator(data_dir)) {
        if (!e.is_regular_file()) continue;
        if (e.path().extension() != ".json") continue;
        auto rel = fs::relative(e.path(), data_dir);
        auto key = rel.replace_extension("").generic_string();
        load_one(e.path(), key);
    }
}

#endif  // TBL_JSON_LIB_NLOHMANN

}  // namespace {{NAMESPACE}}
